### ISSUE TITLE
Can't run on 1.20.1

### ISSUE THREAD

**Issue by deseven** [llndqvst/rconoutputnewline#2]
Hi, I grabbed a [release for 1.20.1 from modrinth](https://modrinth.com/mod/rconoutputnewline/version/0.2.0+1.20.1) and it doesn't work:

```
[09:22:33] [main/WARN]: Error loading class: net/minecraft/server/rcon/RconCommandOutput (java.lang.ClassNotFo
undException: net/minecraft/server/rcon/RconCommandOutput)
[09:22:33] [main/WARN]: @Mixin target net.minecraft.server.rcon.RconCommandOutput was not found modid.mixins.j
son:MixinRconCommandOutput from mod rconoutputnewline
[09:22:33] [main/WARN]: Error loading class: net/minecraft/server/rcon/RconCommandOutput (java.lang.ClassNotFo
undException: net/minecraft/server/rcon/RconCommandOutput)
```

Fabric Loader 0.15.3
fabric-api 0.88.1+1.20.1

Any thoughts?

**Comment by llndqvst** [comment]
Thanks for reporting this! There seems to have been a problem with the build in the github workflow. I was lazy and only tested locally before pushing.

The recent 0.2.1 was a failed try to get it working. I'll have to check the workflow some more to find out where the build goes wrong.

I'll probably have to fix the later versions as well.

**Comment by deseven** [comment]
No worries! In any case, thanks for taking effort to fix a 10 year old Mojang bug :)

**Comment by llndqvst** [comment]
Sorry for taking this long. But I have fixed the gradle build such that the latest 0.2.2 versions on modrinth should work correctly. I have published updates for 1.20.1 and 1.20.4. I plan to publish fixes for other versions during this weekend.

**Comment by deseven** [comment]
Unfortunately I can no longer check it out, because I stopped maintaining the server last week. But I guess someone else would report if something is wrong.

**Comment by llndqvst** [comment]
Okay, well the file from modrinth _works on my machine_ now. I’ll close this issue. Thanks again for notifying me about this.
